json.servie_name profile.service.name
json.servie_character_limit profile.service.character_limit
json.servie_can_schedule profile.service.can_schedule
json.id profile.id.to_s
json.name profile.name
json.avatar_url profile.avatar_url    
json.formatted_username profile.formatted_username
json.service_slug profile.service_slug
json.url profile.url
json.is_connected profile.is_connected